name: CI

on:
  - push
  - pull_request

jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: uname -a
        run: uname -a

      - name: install required packages
        run: sudo apt-get update && sudo apt-get install -y hyperfine

      - name: prepare fastfetch
        run: |
          wget https://github.com/fastfetch-cli/fastfetch/releases/download/2.31.0/fastfetch-linux-amd64.tar.gz
          tar zxvf fastfetch-linux-amd64.tar.gz
          mv fastfetch-linux-amd64/usr/bin/fastfetch fastfetch
          ./fastfetch --version

      - name: prepare crabfetch
        run: |
          wget https://github.com/LivacoNew/CrabFetch/releases/download/v0.5.0/crabfetch-0.5.0_amd64
          mv crabfetch-0.5.0_amd64 crabfetch
          chmod +x crabfetch
          ./crabfetch --version

      - name: run fastfetch
        run: ./fastfetch -c none -s 'title:separator:cpu:gpu:memory:swap:disk:host:display:os:kernel:packages:de:terminal:shell:battery:editor:uptime:locale:media:initsystem:processes:break:colors' --packages-disabled 'APK:BREW:CHOCO:EMERGE:EOPKG:NIX:OPKG:PALUDIS:PKG:PKGTOOL:MACPORTS:SCOOP:SNAP:WINGET:XBPS:AM' --ds-force-drm sys-only --show-errors

      - name: run fastfetch -json
        run: ./fastfetch -c none --format json --stat -s 'title:separator:cpu:gpu:memory:swap:disk:host:display:os:kernel:packages:de:terminal:shell:battery:editor:uptime:locale:media:initsystem:processes:break:colors' --packages-disabled 'APK:BREW:CHOCO:EMERGE:EOPKG:NIX:OPKG:PALUDIS:PKG:PKGTOOL:MACPORTS:SCOOP:SNAP:WINGET:XBPS:AM' --ds-force-drm sys-only --show-errors

      - name: run crabfetch
        run: ./crabfetch

      - name: run hyperfine
        run: hyperfine -w 20 "./fastfetch -c none -s 'title:separator:cpu:gpu:memory:swap:disk:host:display:os:kernel:packages:de:terminal:shell:battery:editor:uptime:locale:media:initsystem:processes:break:colors' --packages-disabled 'APK:BREW:CHOCO:EMERGE:EOPKG:NIX:OPKG:PALUDIS:PKG:PKGTOOL:MACPORTS:SCOOP:SNAP:WINGET:XBPS:AM' --ds-force-drm sys-only" "./crabfetch"
